---
- name: Installing all the requiered packages
  dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"

- name: creating index.html file from ansible jinja2 template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: Starting and enabling the services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ pkgs }}"

- name: Managing firewall rules
  firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ rule }}"
